### ISSUE TITLE
Issue running commands

### ISSUE THREAD

**Issue by thsowers** [c9s/typeloy#15]
When I try to run any commands with typeloy, such as 

`typeloy --config mup.json deploy`

I get the following output:

`
/usr/local/lib/node_modules/typeloy/lib/config.js:12
    return loc.replace('~', process.env.HOME);
              ^

TypeError: Cannot read property 'replace' of undefined
    at expandPath (/usr/local/lib/node_modules/typeloy/lib/config.js:12:15)
    at Function.preprocess (/usr/local/lib/node_modules/typeloy/lib/config.js:78:43)
    at Function.parse (/usr/local/lib/node_modules/typeloy/lib/config.js:35:23)
    at Object.readConfig (/usr/local/lib/node_modules/typeloy/lib/config.js:121:33)
    at Command.<anonymous> (/usr/local/lib/node_modules/typeloy/lib/bin/typeloy.js:22:27)
    at Command.listener (/usr/local/lib/node_modules/typeloy/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:87:13)
    at Command.emit (events.js:172:7)
    at Command.parseArgs (/usr/local/lib/node_modules/typeloy/node_modules/commander/index.js:615:12)
    at Command.parse (/usr/local/lib/node_modules/typeloy/node_modules/commander/index.js:458:21)
`

Not sure what's causing this...if it's of any help `tsv -v` says version 1.8.10

**Comment by c9s** [comment]
Try to ignore the --config mup.json, it will find out the config file
automatically

Tyler Sowers notifications@github.com 於 2016年8月1日 星期一寫道：

**Comment by thsowers** [comment]
Found the issue! I was specifying incorrect SSL parameters from a prior version of mupx. It seems that you need to pass a pem file as the only option to the SSL block
