### ISSUE TITLE
settings.json not found.

### ISSUE THREAD

**Issue by crapthings** [c9s/typeloy#39]
copy example and modified mup file but i've got this

typeloy setup
**WARNING**: settings.json not found.

```
{
  // Server authentication info
  "servers": [
    {
      "host": "ip",
      "username": "user",
      "password": "passwd",
      // or pem file (ssh based authentication)
      //"pem": "~/.ssh/id_rsa",
      // Also, for non-standard ssh port use this
      //"sshOptions": { "port" : 49154 },
      // server specific environment variables
      "env": {}
    }
  ],

  // Install MongoDB on the server. Does not destroy the local MongoDB on future setups
  "setupMongo": true,

  // WARNING: Node.js is required! Only skip if you already have Node.js installed on server.
  "setupNode": true,

  // WARNING: nodeVersion defaults to 0.10.36 if omitted. Do not use v, just the version number.
  "nodeVersion": "4.5.0",

  // Install PhantomJS on the server
  "setupPhantom": true,

  // Show a progress bar during the upload of the bundle to the server.
  // Might cause an error in some rare cases if set to true, for instance in Shippable CI
  "enableUploadProgressBar": true,

  // Application name (no spaces).
  "appName": "pm2meteor",

  // Location of app (local directory). This can reference '~' as the users home directory.
  // i.e., "app": "~/Meteor/my-app",
  // This is the same as the line below.
  "app": "~/dev/deploy-test",

  // Configure environment
  // ROOT_URL must be set to https://YOURDOMAIN.com when using the spiderable package & force SSL
  // your NGINX proxy or Cloudflare. When using just Meteor on SSL without spiderable this is not necessary
  "env": {
    "PORT": 8080,
    "ROOT_URL": "http://ip",
    "MONGO_URL": "mongodb://localhost:27017/pm2meteor"
  },

  // Meteor Up checks if the app comes online just after the deployment.
  // Before mup checks that, it will wait for the number of seconds configured below.
  "deployCheckWaitTime": 120
}
```

**Comment by sean-stanley** [comment]
I tried creating an empty settings.json file with just {"public: {} } inside and still receiving warning followed by no more activity after running `typeloy setup`

I have a mup.json file that was working perfectly fine until I had to upgrade the server to ubuntu 0.16 and upstart doesn't exist any more.

**Comment by c9s** [comment]
reply you soon

Sean Stanley notifications@github.com 於 2016年9月28日 星期三寫道：

**Comment by Testato** [comment]
@sean-stanley 
https://github.com/c9s/typeloy/issues/6

**Comment by sean-stanley** [comment]
Yep, I saw issue #6 and that was actually how I stumbled across this project. It looks like systemd is now supported and labelled complete in the roadmap. Did I misunderstand and this feature is not live in v1.6.0 from npm?

Thank you for your help. Glad to see a maintained project for this.

**Comment by c9s** [comment]
yes, systemd is already integrated and we're already using typelog to deploy meteor 1.3 app to Ubuntu 16.10

**Comment by c9s** [comment]
@sean-stanley what's your dir structure for meteor and settings.json ?

**Comment by sean-stanley** [comment]
my dir structure is (grossly simplified)

```
projectroot -
  client
  deploy
    mup.json
    settings.json
  imports
  server
  package.json
  README.md
```

Is that helpful?

**Comment by Testato** [comment]
i confirm this problem using:
typeloy version 1.6.2
Remote VPS: Ubuntu 16.04 - 64bit
Local PC: Xubuntu 16.04 - 32bit

typeloy setup but also typeloy deploy do not work

```
xubuntu@xubuntu-VirtualBox:~/Desktop/testapp$ typeloy setup
**WARNING**: settings.json not found.
xubuntu@xubuntu-VirtualBox:~/Desktop/testapp$ 
```

```
xubuntu@xubuntu-VirtualBox:~/Desktop/testapp$ typeloy deploy
**WARNING**: settings.json not found.
/home/xubuntu/Downloads/typeloy-master/lib/src/Deployment.js:39
            tag = revInfo.describe;
                         ^
TypeError: Cannot read property 'describe' of null
    at Function.Deployment.create (/home/xubuntu/Downloads/typeloy-master/lib/src/Deployment.js:39:26)
    at Command.<anonymous> (/home/xubuntu/Downloads/typeloy-master/lib/bin/typeloy.js:27:46)
    at Command.listener (/home/xubuntu/Downloads/typeloy-master/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:87:13)
    at Command.emit (events.js:172:7)
    at Command.parseArgs (/home/xubuntu/Downloads/typeloy-master/node_modules/commander/index.js:615:12)
    at Command.parse (/home/xubuntu/Downloads/typeloy-master/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/home/xubuntu/Downloads/typeloy-master/lib/bin/typeloy.js:119:6)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
xubuntu@xubuntu-VirtualBox:~/Desktop/testapp$ ^C
xubuntu@xubuntu-VirtualBox:~/Desktop/testapp$ 
```

And do not forgot that Typeloy loose the Windows compatibility also.

**Comment by c9s** [comment]
thanks

Testato notifications@github.com 於 2016年10月8日 星期六寫道：

**Comment by Testato** [comment]
I can give to you my VPS root password if you need test directly the bug.

**Comment by Testato** [comment]
This morning I cleared my Xubuntu workstation and reinstalled last Meteor (1.4.1.2)
I created a simple Meteor test app, "meteor create testapp"
And also it is not possible Typeloy Setup and Typeloy Deploy

```
xubuntu@xubuntu-VirtualBox:~$ meteor --version
Meteor 1.4.1.2
xubuntu@xubuntu-VirtualBox:~/Desktop/testapp$ typeloy --version
1.6.2
xubuntu@xubuntu-VirtualBox:~/Desktop/testapp$ sudo typeloy setup
[sudo] password for xubuntu: 
**WARNING**: settings.json not found.

xubuntu@xubuntu-VirtualBox:~/Desktop/testapp$ sudo typeloy deploy
path.js:424
    var path = (i >= 0) ? arguments[i] : process.cwd();
                                                 ^

Error: ENOENT: no such file or directory, uv_cwd
    at Error (native)
    at Object.posix.resolve (path.js:424:50)
    at Function.Module._resolveLookupPaths (module.js:250:17)
    at Function.Module._resolveFilename (module.js:317:31)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/xubuntu/Downloads/typeloy-master/lib/bin/typeloy.js:5:16)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
xubuntu@xubuntu-VirtualBox:~/Desktop/testapp$ 

```

**Comment by c9s** [comment]
Thank you for reporting this.

Testato notifications@github.com 於 2016年10月8日 星期六寫道：

**Comment by c9s** [comment]
I released the fixes in 1.6.4

**Comment by c9s** [comment]
@crapthings @sean-stanley to avoid side effect, please use the latest config structure.

See https://github.com/c9s/typeloy/blob/master/example/typeloy.json for example

We've been using this config for our production for 2 months without encountering any issue.

Thank you.

**Comment by Testato** [comment]
ok now the setting.json is founded, but the setup install the old Node 0.10.44 also if i changed the node verison in typeloy.json

```
"setup": {
    "mongo": true,
    "node": "4.6.0",
    "phantom": false
  },
```

And after that it fail also:

```
xubuntu@xubuntu-VirtualBox:~/Desktop/testapp$ typeloy --version
1.6.5
xubuntu@xubuntu-VirtualBox:~/Desktop/testapp$ typeloy setup dev
Found /home/xubuntu/Desktop/testapp/settings.json

Started TaskList: Setup Tasks
[xxx] - Updating package index
[xxx] - Updating package index: SUCCESS
[xxx] - Installing Node.js: 0.10.44
[xxx] - Installing Node.js: 0.10.44: SUCCESS
[xxx] - Setting up shared bash functions
[xxx] x Setting up shared bash functions: FAILED
    Permission denied
✘ Host xxx
  ✔ Updating package index
  ✔ Installing Node.js: 0.10.44
  ✘ Setting up shared bash functions
    Permission denied


```

**Comment by c9s** [comment]
@Testato thanks for reporting this so fast, it's fixed in aa0e882

**Comment by Testato** [comment]
Nope,
same problem also on last master update
1) Old node version installed
2) Permission Denied

```
xubuntu@xubuntu-VirtualBox:~/Desktop/testapp$ typeloy setup dev
Found /home/xubuntu/Desktop/testapp/settings.json

Started TaskList: Setup Tasks
[xxx] - Updating package index
[xxx] - Updating package index: SUCCESS
[xxx] - Installing Node.js: 0.10.44
[xxx] - Installing Node.js: 0.10.44: SUCCESS
[xxx] - Setting up environment for meteor application
[xxx] - Setting up environment for meteor application: SUCCESS
[xxx] - Setting up shared bash functions
[xxx] x Setting up shared bash functions: FAILED
    Permission denied
✘ Host xxx
  ✔ Updating package index
  ✔ Installing Node.js: 0.10.44
  ✔ Setting up environment for meteor application
  ✘ Setting up shared bash functions
    Permission denied

xubuntu@xubuntu-VirtualBox:~/Desktop/testapp$ 

```

**Comment by Testato** [comment]
Same here, also whit the last commit it istall the old Node 0.10.44 and after receive permission denied
I tried also with the master/example/typeloy.json 
I attach it so you can check if there is error

Sorry for the question, but you test typeloy after modification ? You can use an empty Ubuntu16 VM.
On your server do you have Node 4.6.0 ?
Are you installed it by typeloy or manually ?
May you post your typeloy.json ?

```
{
  // Server authentication info
  "sites":{
    "MeteorVPS": {
        "servers": [
            {
                "host": "x.x.x.x",
        "sshOptions": { "port": 822 },
        "username": "xxx",
        "password": "xxx"
                // or pem file (ssh based authentication)
                //"pem": "~/.ssh/id_rsa"
            }
        ],
//         "ssl": {
//            "certbot": {
//                "email": "your@email.com",
//                "domain": "thedomain.com"
//            }
//        },
        "env": {
            // "MAIL_URL":"smtp://support@kaneoh.com:iaiojl5o@0907@smtp.gmail.com:465/",
            // "MONGO_URL": "mongodb://localhost:27017/shaka",
            "ROOT_URL": "http://x.x.x.x",
        "PORT": 3000
        }
    }
  },

  "setup": {
    // Install MongoDB in the server, does not destroy local MongoDB on future setup
    "mongo": true,

    // WARNING: Node.js is required! Only skip if you already have Node.js installed on server.
    "node": "4.6.0",

    // Install PhantomJS in the server
    "phantom": false
  },

  "meteor": {
    // "env": { "PACKAGE_DIRS": "../private-packages" }
  },

  "app": {
    "name": "MeteorVPS",
    "directory": ".",
    "settings": "settings.json"
  },

  "deploy": {
    // Meteor Up checks if the app comes online just after the deployment
    // before mup checks that, it will wait for no. of seconds configured below
    "checkDelay": 10,
    "exposeSiteName": true,
    "exposeVersionInfo": true
  },

  // Show a progress bar during the upload of the bundle to the server. 
  // Might cause an error in some rare cases if set to true, for instance in Shippable CI
  "enableUploadProgressBar": true,

  // Configure common environment for all sites
  "env": {
    // "ROOT_URL": "http://myapp.com"
  }
}
```

**Comment by Testato** [comment]
I installed Manually the NodeJS 4.6.0 on the VPS, so i removed the node installation from typeloy.json
But also in this way remain the Permission Denied error

```
xubuntu@xubuntu-VirtualBox:~/Desktop/testapp$ typeloy setup MeteorVPS
Found /home/xubuntu/Desktop/testapp/settings.json

Started TaskList: Setup Tasks
[xxxx] - Updating package index
[xxxx] - Updating package index: SUCCESS
[xxxx] - Setting up environment for meteor application
[xxxx] - Setting up environment for meteor application: SUCCESS
[xxxx] - Setting up shared bash functions
[xxxx] x Setting up shared bash functions: FAILED
    Permission denied
✘ Host xxxx
  ✔ Updating package index
  ✔ Setting up environment for meteor application
  ✘ Setting up shared bash functions
    Permission denied

xubuntu@xubuntu-VirtualBox:~/Desktop/testapp$ 
```

**Comment by c9s** [comment]
I think it's because your user is not root? and so when creating
/opt/functions.sh you received Permission Denied

Testato notifications@github.com 於 2016年10月9日 星期日寫道：

**Comment by c9s** [comment]
I will create an empty server to test it soon.

Yo-An Lin yoanlin93@gmail.com 於 2016年10月9日 星期日寫道：

**Comment by Testato** [comment]
my user is in the sudoers list and no password required, like the MUP guide
https://github.com/arunoda/meteor-up#ssh-based-authentication-with-sudo

**Comment by Testato** [comment]
this can be useful ?

```
Oct 09 08:52:33 ubuntu sudo[25100]: testatovps : TTY=unknown ; PWD=/home/testatovps ; USER=root ; COMMAND=/usr/local/bin/npm install -g forever userdown wait-for-mongo node-gyp
Oct 09 08:52:33 ubuntu sudo[25100]: pam_unix(sudo:session): session opened for user root by (uid=0)
Oct 09 08:52:54 ubuntu sudo[25100]: pam_unix(sudo:session): session closed for user root
Oct 09 08:52:54 ubuntu sudo[25177]: testatovps : TTY=unknown ; PWD=/home/testatovps ; USER=root ; COMMAND=/usr/sbin/useradd meteoruser
Oct 09 08:52:54 ubuntu sudo[25177]: pam_unix(sudo:session): session opened for user root by (uid=0)
Oct 09 08:52:54 ubuntu useradd[25178]: new group: name=meteoruser, GID=1003
Oct 09 08:52:54 ubuntu useradd[25178]: new user: name=meteoruser, UID=1003, GID=1003, home=/home/meteoruser, shell=
Oct 09 08:52:54 ubuntu sudo[25177]: pam_unix(sudo:session): session closed for user root
Oct 09 08:52:54 ubuntu sshd[25086]: Received disconnect from x.x.x.x port 60860:11:
Oct 09 08:52:54 ubuntu sshd[25086]: Disconnected from x.x.x.x port 60860
Oct 09 08:52:54 ubuntu sshd[25048]: pam_unix(sshd:session): session closed for user testatovps
Oct 09 08:52:54 ubuntu systemd-logind[548]: Removed session 249.
```

**Comment by c9s** [comment]
It's because node ssh copy uses the user session without sudo. I will fix it.

**Comment by c9s** [comment]
@Testato can you try v1.6.6 ? the fixes are included in the patch version.

**Comment by Testato** [comment]
yep, i will try immediately

**Comment by Testato** [comment]
ok, now the shared bash function  permission denied is solved.
Also the topic original setting.json error is solved, so i think that you can close this.

We can continue here :-)
https://github.com/c9s/typeloy/issues/43

**Comment by c9s** [comment]
@Testato thanks!
