### ISSUE TITLE
Ubuntu16 support

### ISSUE THREAD

**Issue by Testato** [c9s/typeloy#6]
My compliments to you for this MUP revive.
The original development go to the mupx side, so docker image, but the origunal MUP idea need to remain active and supported.

One important step is the new Ubuntu support, this mean SystemD support.
Do you working on this ?
https://github.com/kadirahq/meteor-up/issues/148

Thanks for your work, i will support you on forums and whit betates

**Comment by c9s** [comment]
I have some experience with systemd with phpbrew. so it's not too hard to integrate systemd. I can arrange this into the roadmap.

**Comment by Testato** [comment]
Ok,
I will test it on my VPS

**Comment by Testato** [comment]
Ubuntu16.04 is an LTS release, so many server will be updated.
Typeloy will become very popular because it will be the only one that will work :-)

**Comment by c9s** [comment]
Progressing  :)

**Comment by c9s** [comment]
Some resources:
1. https://wiki.ubuntu.com/SystemdForUpstartUsers
2. https://wiki.ubuntu.com/systemd
3. https://github.com/phpbrew/phpbrew/blob/master/src/PhpBrew/Command/FpmCommand/SetupCommand.php

**Comment by c9s** [comment]
Need to add some check function:

``` sh
init_is_upstart()
{
   if [ -x /sbin/initctl ] && /sbin/initctl version 2>/dev/null | /bin/grep -q upstart; then
       return 0
   fi
   return 1
}
```

**Comment by c9s** [comment]
systemd definition file:

```
[Unit]
Description=meteor app
After=network.target
[Service]
Type=notify
PIDFile=.....
WorkingDirectory=/opt/{appName}/....
ExecStart=node main.js
ExecReload=/bin/kill -USR2 \$MAINPID
[Install]
WantedBy=multi-user.target
```

**Comment by Testato** [comment]
Pidfile is a problem, if i remember correctly my  service file do not have it.
May I post it ?

**Comment by c9s** [comment]
sure.

I finished a systemd service config file this afternoon,

changing Type=simple
then we dont need the pidfile

Testato notifications@github.com 於 2016年8月12日 星期五寫道：

**Comment by c9s** [comment]
I am working on the environment file generator right now

**Comment by Testato** [comment]
This is my actual working .service file

[Unit]
Description=MeteorVPS nodejs daemon
After=network.target remote-fs.target

[Service]
User=pippo
Group=pippo
ExecStart=/usr/bin/node /opt/MeteorVPS/app/main.js
Restart=always
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=MeteorVPS
Environment=NODE_ENV=production
Environment=PWD=/opt/MeteorVPS/app/
Environment=PORT=3000
Environment=HTTP_FORWARDED_COUNT=1
Environment=MONGO_URL=mongodb://127.0.0.1:27017/MeteorVPS
Environment=ROOT_URL=http://x.x.x.x

[Install]
WantedBy=multi-user.target

**Comment by c9s** [comment]
```
journalctl -u appName.service -f
```

This will be needed for "logs" command.

**Comment by c9s** [comment]
it works! let me push the branch

**Comment by c9s** [comment]
@Testato it's time to give it a try

Here is the new config file format: https://gist.github.com/c9s/77e3b69d80c31e7a73e52542fce285c5

I am right now preparing the pre-release for npm

**Comment by c9s** [comment]
Done. Please run `npm install -g typeloy@next` to get the latest version. Here is the usage:

```
 typeloy setup [siteName]     # setup the systemd unit file
 typeloy deploy [siteName]   # deploy with systemd
 typeloy logs [siteName]       # see the logs
```

Note:
1.  Please don't use this on production for now, this is a pre-release.
2.  You can configure `init: "systemd"` in site config entry or server config entry to enable systemd for the `logs` command.  See the example config file above.

**Comment by Testato** [comment]
i have two problems (i'm on Win10-64):

```
C:\Users\win10\Desktop\MeteorVPS>typeloy --version
1.3.0
```

if i try to init a new meteor app, typeloy do not create the setting.json+typeloy.json or mup.json files:

```
C:\Users\win10\Desktop\New folder\testapp>typeloy init
config file does not exist! possible config filenames: typeloy.js,typeloy.json,typeloy.config.json,mup.json]

```

if i manually create a typeloy.json and a setting.json file i receive a GIT error, but i do not use GIT on this project.
Typeloy needs GIT ?

```
C:\Users\win10\Desktop\MeteorVPS>typeloy setup dev
Found C:\Users\win10\Desktop\MeteorVPS\settings.json
fatal: Not a git repository: ''C:\Users\win10\Desktop\MeteorVPS\.git''
child_process.js:507
    throw err;
    ^

Error: Command failed: git --git-dir 'C:\Users\win10\Desktop\MeteorVPS\.git' --work-tree 'C:\Users\win10\Desktop\MeteorVPS' describe --tags --abbrev=0
fatal: Not a git repository: ''C:\Users\win10\Desktop\MeteorVPS\.git''

    at checkExecSyncError (child_process.js:464:13)
    at Object.execSync (child_process.js:504:13)
    at GitSync.describeTags (C:\Users\win10\AppData\Roaming\npm\node_modules\typeloy\lib\src\GitSync.js:239:36)
    at parseGitRepo (C:\Users\win10\AppData\Roaming\npm\node_modules\typeloy\lib\src\collectors.js:14:26)
    at Function.GitRevCollector.collect (C:\Users\win10\AppData\Roaming\npm\node_modules\typeloy\lib\src\collectors.js:26:16)
    at Function.Deployment.create (C:\Users\win10\AppData\Roaming\npm\node_modules\typeloy\lib\src\Deployment.js:14:52)
    at Command.<anonymous> (C:\Users\win10\AppData\Roaming\npm\node_modules\typeloy\lib\bin\typeloy.js:43:46)
    at Command.listener (C:\Users\win10\AppData\Roaming\npm\node_modules\typeloy\node_modules\commander\index.js:301:8)
    at emitTwo (events.js:87:13)
    at Command.emit (events.js:172:7)`
```

**Comment by c9s** [comment]
Yes, typeloy use git to parse the deployment information.

I can add an option to switch off this.

**Comment by c9s** [comment]
ok it seems the `init` command is not working.

**Comment by Testato** [comment]
But i tried also tu add git to the meteor project, but it do not work also.
How i can use it ? It is a windows problem ?
I must wait a new typeloy version ?

**Comment by c9s** [comment]
hmm Windows is not garenteed ,
because I dont have Windows to test it,

but I can review the paths used for Windows

Testato notifications@github.com 於 2016年8月15日 星期一寫道：

**Comment by Testato** [comment]
So at moment we must tell that Typeloy loosed the Win compatibility ?
May you use a VM like VirtualBox for win testing ?

**Comment by c9s** [comment]
I fixed few things today, might work now?

Testato notifications@github.com 於 2016年8月15日 星期一寫道：

**Comment by Testato** [comment]
sorry for the question, but how i can update to the actual master branch ?

if i try npm install -g typeloy@next 
it install the old 1.3.0 version

**Comment by c9s** [comment]
you git clone the repo, run

npm install
npm install -g typescript
tsc
npm link

Testato notifications@github.com 於 2016年8月16日 星期二寫道：

**Comment by Testato** [comment]
i do not use git,

i tried:
npm uninstall -g typeloy
npm install -g https://github.com/c9s/typeloy/tarball/master

but it do not work, i need git on windows ?

**Comment by c9s** [comment]
you cant because the compiled js files are not stored on github

Testato notifications@github.com 於 2016年8月16日 星期二寫道：

**Comment by Testato** [comment]
I downloaded the typeloy-master.zip
unzipped and inside it i run 

```
npm install
npm install -g typescript
tsc
npm link
typeloy setup
```

now from two hours it is on

```
C:\Users\win10\Desktop\testapp>typeloy setup
**WARNING**: settings.json not found.
```

But inside the dir i have setting.json, and the cpu of my Win10 continue to work on some nodejs job started from this command.
I think that does not work :-)

**Comment by Testato** [comment]
i can confirm that after a day my PC remain on that WARNING, and do not stop.
I had to kill him

Typeloy is a big improvement on MUP, i think that you should not release a linux/windows compatible version without try it before on a Windows VirtualMachine

**Comment by c9s** [comment]
This is not released yet, so we need more testing base on this.

For now, it works on both OS X and Linux.

Testato notifications@github.com 於 2016年8月17日 星期三寫道：

**Comment by Testato** [comment]
I tried from Linux and it do not work too (xubuntu 32bit)
(Typeloy installed from today github master by your instruction)

Local console log:

```
xubuntu@xubuntu-VirtualBox:~/myapp$ typeloy setup dev
**WARNING**: settings.json not found.
“ Checkout Kadira!
  It's the best way to monitor performance of your app.
  Visit: https://kadira.io/mup ”


Started TaskList: Setup (linux)
[] - Updating package index
[] - Updating package index: SUCCESS
[] - Installing Node.js: 0.10.44
[] x Installing Node.js: 0.10.44: FAILED

    -----------------------------------STDERR-----------------------------------
      6800K .......... .......... .......... .......... .......... 99% 9.03M 0s
      6850K .......... .                                          100%  112M=0.4s

    2016-08-17 05:36:19 (14.9 MB/s) - ‘node-v0.10.44-linux-x64.tar.gz’ saved [7026638/7026638]

    npm ERR! Linux 4.4.0-24-generic
    npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "forever"
    npm ERR! node v0.10.44
    npm ERR! npm  v2.15.0
    npm ERR! path /usr/bin/forever
    npm ERR! code EACCES
    npm ERR! errno 3

    npm ERR! Error: EACCES, unlink '/usr/bin/forever'
    npm ERR!  { [Error: EACCES, unlink '/usr/bin/forever'] errno: 3, code: 'EACCES', path: '/usr/bin/forever' }
    npm ERR! 
    npm ERR! Please try running this command again as root/Administrator.
    npm ERR! error rolling back Error: EACCES, unlink '/usr/bin/forever'
    npm ERR! error rolling back  { [Error: EACCES, unlink '/usr/bin/forever'] errno: 3, code: 'EACCES', path: '/usr/bin/forever' }

    npm ERR! Please include the following file with any support request:
    npm ERR!     /tmp/npm-debug.log
    -----------------------------------STDOUT-----------------------------------
    odules/inherits/
    node-v0.10.44-linux-x64/lib/node_modules/npm/node_modules/inherits/inherits_browser.js
    node-v0.10.44-linux-x64/lib/node_modules/npm/node_modules/inherits/package.json
    node-v0.10.44-linux-x64/lib/node_modules/npm/node_modules/inherits/LICENSE
    node-v0.10.44-linux-x64/lib/node_modules/npm/node_modules/inherits/README.md
    node-v0.10.44-linux-x64/lib/node_modules/npm/node_modules/inherits/test.js
    node-v0.10.44-linux-x64/lib/node_modules/npm/node_modules/inherits/inherits.js
    node-v0.10.44-linux-x64/lib/node_modules/npm/node_modules/umask/
    node-v0.10.44-linux-x64/lib/node_modules/npm/node_modules/umask/package.json
    node-v0.10.44-linux-x64/lib/node_modules/npm/node_modules/umask/LICENSE
    node-v0.10.44-linux-x64/lib/node_modules/npm/node_modules/umask/ChangeLog
    node-v0.10.44-linux-x64/lib/node_modules/npm/node_modules/umask/index.js
    node-v0.10.44-linux-x64/lib/node_modules/npm/node_modules/umask/README.md
    node-v0.10.44-linux-x64/lib/node_modules/npm/node_modules/umask/.npmignore
    ----------------------------------------------------------------------------
```

Remote npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install', '-g', 'forever' ]
2 info using npm@2.15.0
3 info using node@v0.10.44
4 verbose node symlink /usr/bin/node
5 verbose install initial load of /usr/lib/package.json
6 verbose readDependencies loading dependencies from /usr/lib/package.json
7 silly cache add args [ 'forever', null ]
8 verbose cache add spec forever
9 silly cache add parsed spec { raw: 'forever',
9 silly cache add   scope: null,
9 silly cache add   name: 'forever',
9 silly cache add   rawSpec: '',
9 silly cache add   spec: 'latest',
9 silly cache add   type: 'tag' }
10 silly addNamed forever@latest
11 verbose addNamed "latest" is being treated as a dist-tag for forever
12 info addNameTag [ 'forever', 'latest' ]
13 silly mapToRegistry name forever
14 silly mapToRegistry using default registry
15 silly mapToRegistry registry https://registry.npmjs.org/
16 silly mapToRegistry data { raw: 'forever',
16 silly mapToRegistry   scope: null,
16 silly mapToRegistry   name: 'forever',
16 silly mapToRegistry   rawSpec: '',
16 silly mapToRegistry   spec: 'latest',
16 silly mapToRegistry   type: 'tag' }
17 silly mapToRegistry uri https://registry.npmjs.org/forever
18 verbose addNameTag registry:https://registry.npmjs.org/forever not in flight; fetching
19 verbose request uri https://registry.npmjs.org/forever
20 verbose request no auth needed
21 info attempt registry request try #1 at 05:36:20
22 verbose request id da158075582e5339
23 verbose etag "DL5S7GG81YQJKH28IW3YN9ETO"
24 http request GET https://registry.npmjs.org/forever
25 http 304 https://registry.npmjs.org/forever
26 verbose headers { date: 'Wed, 17 Aug 2016 09:36:20 GMT',
26 verbose headers   via: '1.1 varnish',
26 verbose headers   'cache-control': 'max-age=300',
26 verbose headers   etag: '"DL5S7GG81YQJKH28IW3YN9ETO"',
26 verbose headers   age: '0',
26 verbose headers   connection: 'keep-alive',
26 verbose headers   'x-served-by': 'cache-ord1724-ORD',
26 verbose headers   'x-cache': 'HIT',
26 verbose headers   'x-cache-hits': '1',
26 verbose headers   'x-timer': 'S1471426580.942270,VS0,VE32',
26 verbose headers   vary: 'Accept-Encoding' }
27 silly get cb [ 304,
27 silly get   { date: 'Wed, 17 Aug 2016 09:36:20 GMT',
27 silly get     via: '1.1 varnish',
27 silly get     'cache-control': 'max-age=300',
27 silly get     etag: '"DL5S7GG81YQJKH28IW3YN9ETO"',
27 silly get     age: '0',
27 silly get     connection: 'keep-alive',
27 silly get     'x-served-by': 'cache-ord1724-ORD',
27 silly get     'x-cache': 'HIT',
27 silly get     'x-cache-hits': '1',
27 silly get     'x-timer': 'S1471426580.942270,VS0,VE32',
27 silly get     vary: 'Accept-Encoding' } ]
28 verbose etag https://registry.npmjs.org/forever from cache
29 verbose get saving forever to /home/testatovps/.npm/registry.npmjs.org/forever/.cache.json
30 verbose correctMkdir /home/testatovps/.npm correctMkdir not in flight; initializing
31 silly addNameTag next cb for forever with tag latest
32 silly addNamed forever@0.15.2
33 verbose addNamed "0.15.2" is a plain semver version for forever
34 silly cache afterAdd forever@0.15.2
35 verbose afterAdd /home/testatovps/.npm/forever/0.15.2/package/package.json not in flight; writing
36 verbose correctMkdir /home/testatovps/.npm correctMkdir not in flight; initializing
37 verbose afterAdd /home/testatovps/.npm/forever/0.15.2/package/package.json written
38 silly install resolved [ { name: 'forever',
38 silly install resolved     preferGlobal: 'true',
38 silly install resolved     description: 'A simple CLI tool for ensuring that a given node script runs continuously (i.e. forever)',
38 silly install resolved     version: '0.15.2',
38 silly install resolved     author: { name: 'Charlie Robbins', email: 'charlie.robbins@gmail.com' },
38 silly install resolved     maintainers: [ [Object], [Object], [Object], [Object], [Object] ],
38 silly install resolved     repository:
38 silly install resolved      { type: 'git',
38 silly install resolved        url: 'git+https://github.com/foreverjs/forever.git' },
38 silly install resolved     keywords: [ 'cli', 'fault tolerant', 'sysadmin', 'tools' ],
38 silly install resolved     dependencies:
38 silly install resolved      { cliff: '~0.1.9',
38 silly install resolved        clone: '^1.0.2',
38 silly install resolved        colors: '~0.6.2',
38 silly install resolved        flatiron: '~0.4.2',
38 silly install resolved        'forever-monitor': '~1.6.0',
38 silly install resolved        nconf: '~0.6.9',
38 silly install resolved        nssocket: '~0.5.1',
38 silly install resolved        'object-assign': '^3.0.0',
38 silly install resolved        optimist: '~0.6.0',
38 silly install resolved        'path-is-absolute': '~1.0.0',
38 silly install resolved        prettyjson: '^1.1.2',
38 silly install resolved        shush: '^1.0.0',
38 silly install resolved        timespan: '~2.3.0',
38 silly install resolved        utile: '~0.2.1',
38 silly install resolved        winston: '~0.8.1' },
38 silly install resolved     devDependencies:
38 silly install resolved      { broadway: '~0.3.6',
38 silly install resolved        eventemitter2: '0.4.x',
38 silly install resolved        request: '2.x.x',
38 silly install resolved        vows: '0.7.x' },
38 silly install resolved     bin: { forever: './bin/forever' },
38 silly install resolved     main: './lib/forever',
38 silly install resolved     scripts: { test: 'vows test/**/*-test.js --spec -i' },
38 silly install resolved     engines: { node: '>= 0.8.x' },
38 silly install resolved     license: 'MIT',
38 silly install resolved     gitHead: '66e8c0b72aeaa43f814f99ef4bc412db717ebd97',
38 silly install resolved     bugs: { url: 'https://github.com/foreverjs/forever/issues' },
38 silly install resolved     homepage: 'https://github.com/foreverjs/forever#readme',
38 silly install resolved     _id: 'forever@0.15.2',
38 silly install resolved     _shasum: 'fbf21a791ac76bc1a9149a322bc177f338cf5cf9',
38 silly install resolved     _from: 'forever@latest',
38 silly install resolved     _npmVersion: '3.8.9',
38 silly install resolved     _nodeVersion: '4.4.3',
38 silly install resolved     _npmUser: { name: 'indexzero', email: 'charlie.robbins@gmail.com' },
38 silly install resolved     dist:
38 silly install resolved      { shasum: 'fbf21a791ac76bc1a9149a322bc177f338cf5cf9',
38 silly install resolved        tarball: 'https://registry.npmjs.org/forever/-/forever-0.15.2.tgz' },
38 silly install resolved     _npmOperationalInternal:
38 silly install resolved      { host: 'packages-12-west.internal.npmjs.com',
38 silly install resolved        tmp: 'tmp/forever-0.15.2.tgz_1464223373811_0.5428708086255938' },
38 silly install resolved     directories: {},
38 silly install resolved     _resolved: 'https://registry.npmjs.org/forever/-/forever-0.15.2.tgz',
38 silly install resolved     readme: 'ERROR: No README data found!' } ]
39 info install forever@0.15.2 into /usr/lib
40 info installOne forever@0.15.2
41 verbose installOne of forever to /usr/lib not in flight; installing
42 verbose correctMkdir /home/testatovps/.npm/_locks correctMkdir not in flight; initializing
43 verbose lock using /home/testatovps/.npm/_locks/forever-489122e4731fc537.lock for /usr/lib/node_modules/forever
44 silly install write writing forever 0.15.2 to /usr/lib/node_modules/forever
45 verbose unbuild lib/node_modules/forever
46 info preuninstall forever@0.15.2
47 info uninstall forever@0.15.2
48 verbose unbuild rmStuff forever@0.15.2 from /usr/lib/node_modules
49 silly gentlyRm /usr/bin/forever is being gently removed
50 silly gentlyRm verifying /usr is an npm working directory
51 silly gentlyRm containing path /usr is under npm's control, in /usr
52 silly gentlyRm deletion target /usr/bin/forever is under /usr
53 verbose gentlyRm vacuuming from /usr/bin/forever up to /usr
54 silly vacuum-fs removing /usr/bin/forever
55 verbose unlock done using /home/testatovps/.npm/_locks/forever-489122e4731fc537.lock for /usr/lib/node_modules/forever
56 verbose stack Error: EACCES, unlink '/usr/bin/forever'
57 verbose cwd /tmp
58 error Linux 4.4.0-24-generic
59 error argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "forever"
60 error node v0.10.44
61 error npm  v2.15.0
62 error path /usr/bin/forever
63 error code EACCES
64 error errno 3
65 error Error: EACCES, unlink '/usr/bin/forever'
65 error  { [Error: EACCES, unlink '/usr/bin/forever'] errno: 3, code: 'EACCES', path: '/usr/bin/forever' }
66 error Please try running this command again as root/Administrator.
67 verbose exit [ 3, true ]
68 verbose unbuild lib/node_modules/forever
69 info preuninstall forever@0.15.2
70 info uninstall forever@0.15.2
71 verbose unbuild rmStuff forever@0.15.2 from /usr/lib/node_modules
72 silly gentlyRm /usr/bin/forever is being gently removed
73 silly gentlyRm verifying /usr is an npm working directory
74 silly gentlyRm containing path /usr is under npm's control, in /usr
75 silly gentlyRm deletion target /usr/bin/forever is under /usr
76 verbose gentlyRm vacuuming from /usr/bin/forever up to /usr
77 silly vacuum-fs removing /usr/bin/forever
78 error error rolling back Error: EACCES, unlink '/usr/bin/forever'
78 error error rolling back  { [Error: EACCES, unlink '/usr/bin/forever'] errno: 3, code: 'EACCES', path: '/usr/bin/forever' }
```

**Comment by c9s** [comment]
Looks like server side permission issue.

I will fix it tonight.

Testato notifications@github.com 於 2016年8月17日 星期三寫道：

**Comment by c9s** [comment]
Fixed.

1adb006..8e586b0

**Comment by Testato** [comment]
nodejs now work,
but is there a problem whit mongoDB

```
xubuntu@xubuntu-VirtualBox:~/myapp$ typeloy setup dev
**WARNING**: settings.json not found.
“ Checkout Kadira!
  It's the best way to monitor performance of your app.
  Visit: https://kadira.io/mup ”


Started TaskList: Setup (linux)
[] - Updating package index
[] - Updating package index: SUCCESS
[] - Installing Node.js: 0.10.44
[] - Installing Node.js: 0.10.44: SUCCESS
[] - Setting up environment for meteor application
[] - Setting up environment for meteor application: SUCCESS
[] - Copying MongoDB configuration
[] - Copying MongoDB configuration: SUCCESS
[] - Installing MongoDB
[] x Installing MongoDB: FAILED

    -----------------------------------STDERR-----------------------------------
    rm: cannot remove '/var/cache/apt/archives/lock': No such file or directory
    gpg: requesting key 7F0CEB10 from hkp server keyserver.ubuntu.com
    gpg: no valid OpenPGP data found.
    gpg: Total number processed: 0
    gpg: keyserver communications error: keyserver helper general error
    gpg: keyserver communications error: unknown pubkey algorithm
    gpg: keyserver receive failed: unknown pubkey algorithm
    -----------------------------------STDOUT-----------------------------------
    Executing: /tmp/tmp.AjNfrzaOLk/gpg.1.sh --keyserver
    hkp://keyserver.ubuntu.com:80
    --recv
    7F0CEB10
    gpgkeys: key 7F0CEB10 can't be retrieved
    ----------------------------------------------------------------------------
```

And what is this: **WARNING**: settings.json not found. ?
I have it, is this correct ?

settings.json

```
{
  "public": {

  }
}
```

**Comment by c9s** [comment]
xubuntu?  which version?

yeah I need to create an empty app to see the result.

**Comment by Testato** [comment]
Local workstation: Xubuntu16 32bit
Remote server: Ubuntu16 64bit

**Comment by Testato** [comment]
I opened a new issue for tracking the windows support, so we can use this only for SystemD testing from linux to linux machine
https://github.com/c9s/typeloy/issues/35

**Comment by c9s** [comment]
Sure, just fire me bugs in separate issues, so I can inspect the issue and fix it.

**Comment by Testato** [comment]
Is there news on this issue ?
If we will have at least deploy from ubuntu to ubuntu working, it will be an important improvement.

**Comment by c9s** [comment]
will soon continue this work this week

Testato notifications@github.com 於 2016年9月9日 星期五寫道：

**Comment by sean-stanley** [comment]
if this is of interest to anyone here I've started a fork of M4v3R's meteor-up fork and removed upstart replacing it with systemd support inspired by typeloy's work.

It has worked great for me so if anyone else is having trouble they can clone and npm link my repo (not published to npm yet sorry).

[https://github.com/sean-stanley/meteor-up/](https://github.com/sean-stanley/meteor-up/)

**Comment by c9s** [comment]
I don't know why the default mup runs `rm /var/apt....`

**Comment by c9s** [comment]
@sean-stanley @Testato fixed the mongo setup last night, could you try it again?

**Comment by Testato** [comment]
https://github.com/c9s/typeloy/issues/43

**Comment by c9s** [comment]
@sean-stanley @Testato btw, we just open sourced the continuous deployment integration tool on GitHub. Will update the setup document for the delivery tool soon.

Project: https://github.com/kaneoh/delivery

![screen shot 2016-10-10 at 16 25 54](https://cloud.githubusercontent.com/assets/50894/19230442/1106d12a-8f07-11e6-99fe-3ee538a8e38c.png)

**Comment by c9s** [comment]
doc updated https://github.com/kaneoh/delivery

**Comment by Testato** [comment]
Good news, 
I will test it when typeloy will work on my vps

**Comment by Testato** [comment]
Solved, thanks
